name: Deploy Updates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Deploy preview update for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Deploying preview update for PR #${{ github.event.number }}"
          eas update --branch preview --message "Preview update for PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}"

      - name: Deploy production update on main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Deploying production update"
          eas update --branch production --message "Auto-update from commit ${{ github.sha }}: ${{ github.event.head_commit.message }}"

      - name: Comment on PR with update info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview update deployed! Users with preview builds will receive this update automatically.'
            })

      - name: Comment on main push with update info
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commit } = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: '✅ Production update deployed! Users will receive this update automatically on next app launch.'
            }); 