name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build preview for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Building preview for PR #${{ github.event.number }}"
          eas build --platform all --profile preview --non-interactive --message "Preview build for PR #${{ github.event.number }}"

      - name: Build production on main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Building production for main branch"
          eas build --platform all --profile production --non-interactive --message "Production build from commit ${{ github.sha }}"

      - name: Deploy OTA update on main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Deploying OTA update to production channel"
          eas update --branch production --message "Auto-update from commit ${{ github.sha }}: ${{ github.event.head_commit.message }}"

      - name: Comment on PR with build info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview build started! Check the Actions tab for progress.'
            }) 